package rest.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import rest.repository.GameRepository;
import rest.repository.RoomRepository;
import rest.repository.UserRepository;
import rest.entity.Game;
import rest.entity.Room;
import rest.entity.User;

@Controller
@RequestMapping(path = "/")
public class MainController {
    @Autowired // This means to get the bean called Repositories
    // Which are auto-generated by Spring, we will use it to handle the data
    private UserRepository usersRepository;
    @Autowired private RoomRepository roomRepository;
    @Autowired private GameRepository gameRepository;

    @PostMapping(path = "/games")
    public @ResponseBody
    String addNewGame(@RequestParam String gameName) {
        Game newGame = new Game();
        newGame.setGameName(gameName);
        gameRepository.save(newGame);
        return "Game created";
    }


    @PostMapping(path = "/rooms")
    public @ResponseBody
    String addNewRoom(@RequestParam String roomName, @RequestParam Integer gameId, @RequestParam Integer userId) {
        Room newRoom = new Room();
        newRoom.setRoomName(roomName);
        newRoom.setGameId(gameId);
        newRoom.setUserId(userId);
        roomRepository.save(newRoom);
        return "Room Created";
    }

    @GetMapping(path = "/games")
    public @ResponseBody
    Iterable<Game> getAllGames() {
        return gameRepository.findAll();
    }

    @GetMapping(path = "/rooms")
    public @ResponseBody
    Iterable<Room> getAllRooms() {
        return roomRepository.findAll();
    }
//curl localhost:5000/rooms -d roomName=TicTacToeGame -d gameId=6 -d userId=10
//curl http://server-env.eba-xyvg76az.eu-central-1.elasticbeanstalk.com/users -d userName=TicTacToeGame -d password=nu_am_parola
//curl -X DELETE http://localhost:5000/users/10
//curl http://server-env.eba-xyvg76az.eu-central-1.elasticbeanstalk.com/users -d userName=TicTacToeGame -d password=nu_am_parola
}



